---
title: "Introduction to R"
author: "Nayad"
date: "2024-08-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
A = 10
B = 20
A + B
```

# Data Structures in R

## Vectors

```{r}
names <- c("Nayad", "John", "James", "Andy", "George")
age <- c(20, 25, 27, 30, 31)
salaries <- c(1000, 4000, 3000, 2500, 5000)
names (age) <- names
age ["Nayad"]
age [2]# indexing
age[3:5]
age [c(3,5)]# slicing
```
### Factors

```{r}
height <- c("high", "low", "mid", "low", "high")
height1 <- factor(height, levels = c("low", "mid", "high"))
height1
```

## Matrix
```{r}
math <- c(70, 85, 92)
english <- c(65, 74, 82)
social_studies <- c(56, 85, 75)

lessons <- matrix(c(math, english, social_studies), nrow = 3, byrow = TRUE)
lessons
rownames(lessons) <- c("math", "english", "social_studies")
colnames(lessons) <- c("term1", "term2", "term3")
lessons
colSums(lessons)
lessons1 <- rbind(lessons, colSums(lessons))
lessons2 <- cbind(lessons1, rowMeans(lessons1))
lessons2
math_lessons <- lessons[1, ]
math_lessons
```

## List

```{r}

names <- c("Frank", "James", "Hanna", "Aman", "Lisa")
age <- c(24, 30, 27, 15, 21)
employed <- c(TRUE, TRUE, FALSE, FALSE, TRUE)

my_list <- list(names = names, age = age, employed = employed)


my_list$names[1]
my_list[1, ]

my_list
```


## Data Frames

```{r}
```

```{r}
planets <- c("mercruy", "venus", "earth", "mars")
type <- c("uninhabitable", "unhabitable", "inhabitable", "uninhabitable")
number <- c(1, 2, 3, 4)
df2 <- data.frame(planets = planets, type = type, number = number)
df2
```

```{r}
df <- data.frame(names = names, age = age)
df
```

```{r}
library(readr)
Iris <- read_csv("Iris.csv")
```


```{r}
library(readxl)
Iris <- read_excel("Iris.xlsx", sheet = "Iris")
head(Iris)
```

